### ISSUE TITLE
Wrong behavior on DSL resources with 0 arguments

### ISSUE THREAD

**Issue by andis** [sometimesfood/wright#5]
When using the Wright DSL, missing arguments for resources are passed on too far:

```
bundle exec bin/wright -e 'symlink'
ERROR: symlink: undefined method `start_with?' for nil:NilClass
```

Instead, the error should be similar to this:

```
bundle exec bin/wright -e 'symlink(1,2,3,4,5)'
wright/lib/wright/dsl.rb:44:in `block in register_resource': wrong number of arguments (5 for 1) (ArgumentError)
```

**Comment by sometimesfood** [comment]
To be honest, I'm not perfectly happy with the second error message either. `block in register_resource` is somewhat less descriptive than `symlink`.

But of course this should at least be consistent.
